import type { Catalog } from "@iconic/schema";

import { serialize } from "./util";

/**
 * Renders the generated `iconic.config.ts`: a header marking it generated, the
 * one import, and the configuration literal. `sets` is emitted only when the
 * config has any, so a base-only config stays clean. The consumer's TypeScript
 * infers the contract from the literal — full type safety lands there, not here.
 *
 * @param catalog - The resolved, validated catalog.
 * @param source - A label for the header naming what it was generated from.
 */
export const emit = (catalog: Catalog, source: string): string => {
  const document: { base: Catalog["base"]; sets?: Catalog["sets"] } = {
    base: catalog.base,
  };
  if (Object.keys(catalog.sets).length > 0) {
    document.sets = catalog.sets;
  }
  const config = serialize(document, "");
  return [
    "/**",
    ` * Generated by @iconic/iconify from ${source}.`,
    " * Do not edit by hand — regenerate from the ref config.",
    " */",
    `import { defineIconicConfig } from "iconic/config";`,
    "",
    `export default defineIconicConfig(${config});`,
    "",
  ].join("\n");
};
